clone:
  path: git.fidetech.io/bradley/Rocket.Chat.Minecraft

build:
  image: jamesdbloom/docker-java8-maven
  commands:
    - mvn clean install

notify:
  email:
    recipients:
      - bradley@fidetech.io
