clone:
  path: git.fidetech.io/bradley/Rocket.Chat.Minecraft

build:
  image: jamesdbloom/docker-java8-maven
  commands:
    - mvn clean install deploy

notify:
  slack:
    webhook_url: https://chat.fidetech.io/hooks/cpxX2EtNcZQybc3tk/HDka7RrrsL8uWQaifZzgTegNrHqNExN5QewCoqMRt4JxPjhB
    channel: rocket.chat
