clone:
  path: git.fidetech.io/bradley/Rocket.Chat.Minecraft

build:
  image: jamesdbloom/docker-java8-maven
  commands:
    - mvn clean install

publish:
  drone-mvn:
    image: thomasf/drone-mvn
    username: $$MVN_USERNAME
    password: $$MVN_PASSWORD
    url: https://repo.craftyn.com/repository/graywolf336-snapshots/
    group: com.graywolf336
    artifact: rocket.chat
    version: SNAPSHOT
    source: target/*.jar
    extension: jar

    when:
      branch: master

notify:
  slack:
    webhook_url: $$ROCKET_URL
    channel: rocket.chat
