clone:
  path: git.fidetech.io/bradley/Rocket.Chat.Minecraft

build:
  image: jamesdbloom/docker-java8-maven
  commands:
    - mvn clean install

publish:
  drone-mvn:
    image: thomasf/drone-mvn
    username: deployment
    password: admin469_
    url: https://repo.craftyn.com/repository/graywolf336-snapshots/
    group: com.graywolf336
    artifact: rocket.chat
    version: SNAPSHOT
    source: target/*.jar
    extension: jar

    when:
      branch: master

notify:
  slack:
    webhook_url: https://chat.fidetech.io/hooks/cpxX2EtNcZQybc3tk/HDka7RrrsL8uWQaifZzgTegNrHqNExN5QewCoqMRt4JxPjhB
    channel: rocket.chat
